// Working on img urls for in here!

export const projects = [
  {
    name: 'Bob',
    project_interest: 'Sports',
    project_type: 'Blog',
    strength: 'Backend',
    availability: 'Evenings',
    img: 'https://i.imgur.com/a6WqdTd.png',
  },
  {
    name: 'Jim',
    project_interest: 'Games',
    project_type: 'Gallery',
    strength: 'Frontend',
    availability: 'Evenings',
    img: 'https://imgur.com/a/pTaNkgO',
  },
  {
    name: 'Ella',
    project_interest: 'Photography',
    project_type: 'Gallery',
    strength: 'Backend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/BjgOgCo.png',
  },
  {
    name: 'Sally',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Testing',
    availability: 'Weekends',
    img: 'https://i.imgur.com/iKOABlY.png',
  },
  {
    name: 'Penny',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Testing',
    availability: 'Evenings',
    img: 'https://i.imgur.com/u1XTsdQ.png',
  },
  {
    name: 'Roger',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Testing',
    availability: 'Flexible',
    img: 'https://i.imgur.com/NXJJ9RA.png',
  },
  {
    name: 'Peter',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Testing',
    availability: 'Weekends',
    img: 'https://imgur.com/a/pTaNkgO',
  },
  {
    name: 'Oscar',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Frontend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/zuqUYvz.png',
  },
  {
    name: 'Sarah',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Backend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/2lJm97s.png',
  },
  {
    name: 'Emma',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Fullstack',
    availability: 'Weekends',
    img: 'https://i.imgur.com/y67HEDI.png',
  },
  {
    name: 'Roman',
    project_interest: 'Games',
    project_type: 'Forum',
    strength: 'Backend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/YbIU2YV.png',
  },
  {
    name: 'Anthony',
    project_interest: 'Games',
    project_type: 'Blog',
    strength: 'Frontend',
    availability: 'Evenings',
    img: 'https://i.imgur.com/UzGikhS.png',
  },
  {
    name: 'Marie',
    project_interest: 'Games',
    project_type: 'Forum',
    strength: 'Testing',
    availability: 'Flexible',
    img: 'https://i.imgur.com/D8Pcfdo.png',
  },
  {
    name: 'Pablo',
    project_interest: 'Games',
    project_type: 'To-do List',
    strength: 'Fullstack',
    availability: 'Weekends',
    img: 'https://i.imgur.com/nIPGuzQ.png',
  },
  {
    name: 'Eponine',
    project_interest: 'Games',
    project_type: 'Survey',
    strength: 'Fullstack',
    availability: 'Flexible',
    img: 'https://i.imgur.com/oNfY7Ae.png',
  },
  {
    name: 'Leyla',
    project_interest: 'Photography',
    project_type: 'Forum',
    strength: 'Fullstack',
    availability: 'Flexible',
    img: 'https://i.imgur.com/OosXG7U.png',
  },
  {
    name: 'Corinne',
    project_interest: 'Photography',
    project_type: 'Blog',
    strength: 'Frontend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/iKOABlY.png',
  },
  {
    name: 'Claire',
    project_interest: 'Photography',
    project_type: 'To-do List',
    strength: 'Backend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/oNfY7Ae.png',
  },
  {
    name: 'Alex',
    project_interest: 'Sports',
    project_type: 'To-do List',
    strength: 'Backend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/UzGikhS.png',
  },
  {
    name: 'Maxime',
    project_interest: 'Sports',
    project_type: 'Blog',
    strength: 'Frontend',
    availability: 'Flexible',
    img: 'https://i.imgur.com/YbIU2YV.png',
  },
  {
    name: 'Ola',
    project_interest: 'Sports',
    project_type: 'Gallery',
    strength: 'Fullstack',
    availability: 'Weekends',
    img: 'https://i.imgur.com/SBQiwtW.png',
  },
  {
    name: 'Remi',
    project_interest: 'Sports',
    project_type: 'Survey',
    strength: 'Backend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/nIPGuzQ.png',
  },
  {
    name: 'Clara',
    project_interest: 'Sports',
    project_type: 'Gallery',
    strength: 'Backend',
    availability: 'Evenings',
    img: 'https://i.imgur.com/D8Pcfdo.png',
  },
  {
    name: 'Ali',
    project_interest: 'Sports',
    project_type: 'Forum',
    strength: 'Frontend',
    availability: 'Flexible',
    img: 'https://i.imgur.com/J5BqqcT.png',
  },
  {
    name: 'Laith',
    project_interest: 'Games',
    project_type: 'Blog',
    strength: 'Backend',
    availability: 'Weekends',
    img: 'https://imgur.com/a/0LINwUN',
  },
  {
    name: 'Ibrahim',
    project_interest: 'Games',
    project_type: 'Forum',
    strength: 'Backend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/J5BqqcT.png',
  },
  {
    name: 'Leonie',
    project_interest: 'Sports',
    project_type: 'To-do List',
    strength: 'Frontend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/xDBI7hj.png',
  },
  {
    name: 'Nesma',
    project_interest: 'Photography',
    project_type: 'Gallery',
    strength: 'Backend',
    availability: 'Flexible',
    img: 'https://i.imgur.com/BjgOgCo.png',
  },
  {
    name: 'Yasmin',
    project_interest: 'Photography',
    project_type: 'Forum',
    strength: 'Backend',
    availability: 'Weekends',
    img: 'https://i.imgur.com/kygDWAv.png',
  },
  {
    name: 'Diego',
    project_interest: 'Sports',
    project_type: 'Survey',
    strength: 'Backend',
    availability: 'Flexible',
    img: 'https://imgur.com/a/0LINwUN',
  },
  {
    name: 'Harry',
    project_interest: 'Photography',
    project_type: 'Gallery',
    strength: 'Fullstack',
    availability: 'Evenings',
    img: 'https://i.imgur.com/zuqUYvz.png',
  },
  {
    name: 'Luna',
    project_interest: 'Games',
    project_type: 'Blog',
    strength: 'Backend',
    availability: 'Evenings',
    img: 'https://i.imgur.com/OosXG7U.png',
  },
  {
    name: 'Imaan',
    project_interest: 'Photgraphy',
    project_type: 'Blog',
    strength: 'Fullstack',
    availability: 'Flexible',
    img: 'https://i.imgur.com/BjgOgCo.png',
  },
  {
    name: 'Annabel',
    project_interest: 'Games',
    project_type: 'Survey',
    strength: 'Frontend',
    availability: 'Evenings',
    img: 'https://i.imgur.com/QBwwT0Q.png',
  },
  {
    name: 'Natalja',
    project_interest: 'Sports',
    project_type: 'Blog',
    strength: 'Frontend',
    availability: 'Evenings',
    img: 'https://i.imgur.com/xDBI7hj.png',
  },
  {
    name: 'Konstantin',
    project_interest: 'Games',
    project_type: 'To-do list',
    strength: 'Backend',
    availability: 'Evenings',
    img: 'https://i.imgur.com/NXJJ9RA.png',
  },
  {
    name: 'Adi',
    project_interest: 'Games',
    project_type: 'Gallery',
    strength: 'Fullstack',
    availability: 'Flexible',
    img: 'https://i.imgur.com/SBQiwtW.png',
  },
  {
    name: 'Yune-Keow',
    project_interest: 'Photgraphy',
    project_type: 'Survey',
    strength: 'Fullstack',
    availability: 'Flexible',
    img: 'https://i.imgur.com/UzGikhS.png',
  },
  {
    name: 'Shivani',
    project_interest: 'Sports',
    project_type: 'Gallery',
    strength: 'Fullstack',
    availability: 'Evenings',
    img: 'https://i.imgur.com/kygDWAv.png',
  },
  {
    name: 'Rivkah',
    project_interest: 'Fashion',
    project_type: 'Gallery',
    strength: 'Fullstack',
    availability: 'Evenings',
    img: 'https://i.imgur.com/y67HEDI.png',
  },
];
