// Working on img urls for in here!

export const projects = [
  {
    name: 'Bob',
    project_interest: 'Sports',
    project_type: 'Blog',
    strength: 'Backend',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Jim',
    project_interest: 'Games',
    project_type: 'Games',
    strength: 'Frontend',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Ella',
    project_interest: 'Photography',
    project_type: 'Gallery',
    strength: 'Backend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Sally',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Testing',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Penny',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Testing',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Roger',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Testing',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Peter',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Testing',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Oscar',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Frontend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Sarah',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Backend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Emma',
    project_interest: 'Fashion',
    project_type: 'Forum',
    strength: 'Fullstack',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Roman',
    project_interest: 'Games',
    project_type: 'Forum',
    strength: 'Backend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Anthony',
    project_interest: 'Games',
    project_type: 'Blog',
    strength: 'Frontend',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Marie',
    project_interest: 'Games',
    project_type: 'Forum',
    strength: 'Testing',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Pablo',
    project_interest: 'Games',
    project_type: 'To-do List',
    strength: 'Fullstack',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Eponine',
    project_interest: 'Games',
    project_type: 'Survey',
    strength: 'Fullstack',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Leyla',
    project_interest: 'Photography',
    project_type: 'Forum',
    strength: 'Fullstack',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Corinne',
    project_interest: 'Photography',
    project_type: 'Blog',
    strength: 'Frontend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Claire',
    project_interest: 'Photography',
    project_type: 'To-do List',
    strength: 'Backend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Alex',
    project_interest: 'Sports',
    project_type: 'To-do List',
    strength: 'Backend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Maxime',
    project_interest: 'Sports',
    project_type: 'Blog',
    strength: 'Frontend',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Ola',
    project_interest: 'Sports',
    project_type: 'Gallery',
    strength: 'Fullstack',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Remi',
    project_interest: 'Sports',
    project_type: 'Survey',
    strength: 'Backend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Clara',
    project_interest: 'Sports',
    project_type: 'Gallery',
    strength: 'Backend',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Ali',
    project_interest: 'Sports',
    project_type: 'Forum',
    strength: 'Frontend',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Laith',
    project_interest: 'Games',
    project_type: 'Blog',
    strength: 'Backend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Ibrahim',
    project_interest: 'Games',
    project_type: 'Forum',
    strength: 'Backend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Leonie',
    project_interest: 'Sports',
    project_type: 'To-do List',
    strength: 'Frontend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Nesma',
    project_interest: 'Photography',
    project_type: 'Gallery',
    strength: 'Backend',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Yasmin',
    project_interest: 'Photography',
    project_type: 'Forum',
    strength: 'Backend',
    availability: 'Weekends',
    img: '',
  },
  {
    name: 'Diego',
    project_interest: 'Sports',
    project_type: 'Survey',
    strength: 'Backend',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Harry',
    project_interest: 'Photography',
    project_type: 'Gallery',
    strength: 'Fullstack',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Luna',
    project_interest: 'Games',
    project_type: 'Blog',
    strength: 'Backend',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Imaan',
    project_interest: 'Photgraphy',
    project_type: 'Blog',
    strength: 'Fullstack',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Annabel',
    project_interest: 'Games',
    project_type: 'Survey',
    strength: 'Frontend',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Natalja',
    project_interest: 'Sports',
    project_type: 'Blog',
    strength: 'Frontend',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Konstantin',
    project_interest: 'Games',
    project_type: 'To-do list',
    strength: 'Backend',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Adi',
    project_interest: 'Games',
    project_type: 'Gallery',
    strength: 'Fullstack',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Yune-Keow',
    project_interest: 'Photgraphy',
    project_type: 'Survey',
    strength: 'Fullstack',
    availability: 'Flexible',
    img: '',
  },
  {
    name: 'Shivani',
    project_interest: 'Sports',
    project_type: 'Gallery',
    strength: 'Fullstack',
    availability: 'Evenings',
    img: '',
  },
  {
    name: 'Rivkah',
    project_interest: 'Fashion',
    project_type: 'Gallery',
    strength: 'Fullstack',
    availability: 'Evenings',
    img: '',
  },
];
